; Pokemon Habitats
	const_def
	const GRASSLAND_HABITAT
	const FOREST_HABITAT
	const WATERS_EDGE_HABITAT
	const SEA_HABITAT
	const CAVE_HABITAT
	const MOUNTAIN_HABITAT
	const ROUGH_TERRAIN_HABITAT
	const URBAN_HABITAT
	const RARE_HABITAT
DEF NUM_HABITATS EQU const_value

DEF NO_HABITAT EQU -1
