FollowingSpritePointers::
	dba BulbasaurFollowingSprite
	dba IvysaurFollowingSprite
	dba VenusaurFollowingSprite
	dba CharmanderFollowingSprite
	dba CharmeleonFollowingSprite
	dba CharizardFollowingSprite
	dba SquirtleFollowingSprite
	dba WartortleFollowingSprite
	dba BlastoiseFollowingSprite
	dba CaterpieFollowingSprite
	dba MetapodFollowingSprite
	dba ButterfreeFollowingSprite
	dba WeedleFollowingSprite
	dba KakunaFollowingSprite
	dba BeedrillFollowingSprite
	dba PidgeyFollowingSprite
	dba PidgeottoFollowingSprite
	dba PidgeotFollowingSprite
	dba RattataFollowingSprite
	dba RaticateFollowingSprite
	dba SpearowFollowingSprite
	dba FearowFollowingSprite
	dba EkansFollowingSprite
	dba ArbokFollowingSprite
	dba PikachuFollowingSprite
	dba RaichuFollowingSprite
	dba SandshrewFollowingSprite
	dba SandslashFollowingSprite
	dba Nidoran_fFollowingSprite
	dba NidorinaFollowingSprite
	dba NidoqueenFollowingSprite
	dba Nidoran_mFollowingSprite
	dba NidorinoFollowingSprite
	dba NidokingFollowingSprite
	dba ClefairyFollowingSprite
	dba ClefableFollowingSprite
	dba VulpixFollowingSprite
	dba NinetalesFollowingSprite
	dba JigglypuffFollowingSprite
	dba WigglytuffFollowingSprite
	dba ZubatFollowingSprite
	dba GolbatFollowingSprite
	dba OddishFollowingSprite
	dba GloomFollowingSprite
	dba VileplumeFollowingSprite
	dba ParasFollowingSprite
	dba ParasectFollowingSprite
	dba VenonatFollowingSprite
	dba VenomothFollowingSprite
	dba DiglettFollowingSprite
	dba DugtrioFollowingSprite
	dba MeowthFollowingSprite
	dba PersianFollowingSprite
	dba PsyduckFollowingSprite
	dba GolduckFollowingSprite
	dba MankeyFollowingSprite
	dba PrimeapeFollowingSprite
	dba GrowlitheFollowingSprite
	dba ArcanineFollowingSprite
	dba PoliwagFollowingSprite
	dba PoliwhirlFollowingSprite
	dba PoliwrathFollowingSprite
	dba AbraFollowingSprite
	dba KadabraFollowingSprite
	dba AlakazamFollowingSprite
	dba MachopFollowingSprite
	dba MachokeFollowingSprite
	dba MachampFollowingSprite
	dba BellsproutFollowingSprite
	dba WeepinbellFollowingSprite
	dba VictreebelFollowingSprite
	dba TentacoolFollowingSprite
	dba TentacruelFollowingSprite
	dba GeodudeFollowingSprite
	dba GravelerFollowingSprite
	dba GolemFollowingSprite
	dba PonytaFollowingSprite
	dba RapidashFollowingSprite
	dba SlowpokeFollowingSprite
	dba SlowbroFollowingSprite
	dba MagnemiteFollowingSprite
	dba MagnetonFollowingSprite
	dba Farfetch_dFollowingSprite
	dba DoduoFollowingSprite
	dba DodrioFollowingSprite
	dba SeelFollowingSprite
	dba DewgongFollowingSprite
	dba GrimerFollowingSprite
	dba MukFollowingSprite
	dba ShellderFollowingSprite
	dba CloysterFollowingSprite
	dba GastlyFollowingSprite
	dba HaunterFollowingSprite
	dba GengarFollowingSprite
	dba OnixFollowingSprite
	dba DrowzeeFollowingSprite
	dba HypnoFollowingSprite
	dba KrabbyFollowingSprite
	dba KinglerFollowingSprite
	dba VoltorbFollowingSprite
	dba ElectrodeFollowingSprite
	dba ExeggcuteFollowingSprite
	dba ExeggutorFollowingSprite
	dba CuboneFollowingSprite
	dba MarowakFollowingSprite
	dba HitmonleeFollowingSprite
	dba HitmonchanFollowingSprite
	dba LickitungFollowingSprite
	dba KoffingFollowingSprite
	dba WeezingFollowingSprite
	dba RhyhornFollowingSprite
	dba RhydonFollowingSprite
	dba ChanseyFollowingSprite
	dba TangelaFollowingSprite
	dba KangaskhanFollowingSprite
	dba HorseaFollowingSprite
	dba SeadraFollowingSprite
	dba GoldeenFollowingSprite
	dba SeakingFollowingSprite
	dba StaryuFollowingSprite
	dba StarmieFollowingSprite
	dba Mr_mimeFollowingSprite
	dba ScytherFollowingSprite
	dba JynxFollowingSprite
	dba ElectabuzzFollowingSprite
	dba MagmarFollowingSprite
	dba PinsirFollowingSprite
	dba TaurosFollowingSprite
	dba MagikarpFollowingSprite
	dba GyaradosFollowingSprite
	dba LaprasFollowingSprite
	dba DittoFollowingSprite
	dba EeveeFollowingSprite
	dba VaporeonFollowingSprite
	dba JolteonFollowingSprite
	dba FlareonFollowingSprite
	dba PorygonFollowingSprite
	dba OmanyteFollowingSprite
	dba OmastarFollowingSprite
	dba KabutoFollowingSprite
	dba KabutopsFollowingSprite
	dba AerodactylFollowingSprite
	dba SnorlaxFollowingSprite
	dba ArticunoFollowingSprite
	dba ZapdosFollowingSprite
	dba MoltresFollowingSprite
	dba DratiniFollowingSprite
	dba DragonairFollowingSprite
	dba DragoniteFollowingSprite
	dba MewtwoFollowingSprite
	dba MewFollowingSprite
	dba ChikoritaFollowingSprite
	dba BayleefFollowingSprite
	dba MeganiumFollowingSprite
	dba CyndaquilFollowingSprite
	dba QuilavaFollowingSprite
	dba TyphlosionFollowingSprite
	dba TotodileFollowingSprite
	dba CroconawFollowingSprite
	dba FeraligatrFollowingSprite
	dba SentretFollowingSprite
	dba FurretFollowingSprite
	dba HoothootFollowingSprite
	dba NoctowlFollowingSprite
	dba LedybaFollowingSprite
	dba LedianFollowingSprite
	dba SpinarakFollowingSprite
	dba AriadosFollowingSprite
	dba CrobatFollowingSprite
	dba ChinchouFollowingSprite
	dba LanturnFollowingSprite
	dba PichuFollowingSprite
	dba CleffaFollowingSprite
	dba IgglybuffFollowingSprite
	dba TogepiFollowingSprite
	dba TogeticFollowingSprite
	dba NatuFollowingSprite
	dba XatuFollowingSprite
	dba MareepFollowingSprite
	dba FlaaffyFollowingSprite
	dba AmpharosFollowingSprite
	dba BellossomFollowingSprite
	dba MarillFollowingSprite
	dba AzumarillFollowingSprite
	dba SudowoodoFollowingSprite
	dba PolitoedFollowingSprite
	dba HoppipFollowingSprite
	dba SkiploomFollowingSprite
	dba JumpluffFollowingSprite
	dba AipomFollowingSprite
	dba SunkernFollowingSprite
	dba SunfloraFollowingSprite
	dba YanmaFollowingSprite
	dba WooperFollowingSprite
	dba QuagsireFollowingSprite
	dba EspeonFollowingSprite
	dba UmbreonFollowingSprite
	dba MurkrowFollowingSprite
	dba SlowkingFollowingSprite
	dba MisdreavusFollowingSprite
	dba UnownFollowingSprite
	dba WobbuffetFollowingSprite
	dba GirafarigFollowingSprite
	dba PinecoFollowingSprite
	dba ForretressFollowingSprite
	dba DunsparceFollowingSprite
	dba GligarFollowingSprite
	dba SteelixFollowingSprite
	dba SnubbullFollowingSprite
	dba GranbullFollowingSprite
	dba QwilfishFollowingSprite
	dba ScizorFollowingSprite
	dba ShuckleFollowingSprite
	dba HeracrossFollowingSprite
	dba SneaselFollowingSprite
	dba TeddiursaFollowingSprite
	dba UrsaringFollowingSprite
	dba SlugmaFollowingSprite
	dba MagcargoFollowingSprite
	dba SwinubFollowingSprite
	dba PiloswineFollowingSprite
	dba CorsolaFollowingSprite
	dba RemoraidFollowingSprite
	dba OctilleryFollowingSprite
	dba DelibirdFollowingSprite
	dba MantineFollowingSprite
	dba SkarmoryFollowingSprite
	dba HoundourFollowingSprite
	dba HoundoomFollowingSprite
	dba KingdraFollowingSprite
	dba PhanpyFollowingSprite
	dba DonphanFollowingSprite
	dba Porygon2FollowingSprite
	dba StantlerFollowingSprite
	dba SmeargleFollowingSprite
	dba TyrogueFollowingSprite
	dba HitmontopFollowingSprite
	dba SmoochumFollowingSprite
	dba ElekidFollowingSprite
	dba MagbyFollowingSprite
	dba MiltankFollowingSprite
	dba BlisseyFollowingSprite
	dba RaikouFollowingSprite
	dba EnteiFollowingSprite
	dba SuicuneFollowingSprite
	dba LarvitarFollowingSprite
	dba PupitarFollowingSprite
	dba TyranitarFollowingSprite
	dba LugiaFollowingSprite
	dba Ho_ohFollowingSprite
	dba CelebiFollowingSprite
	db 0, 0, 0
	dba EggFollowingSprite

UnownFollowingSpritePointers::
	dba UNOWN_AFollowingSprite
	dba UNOWN_BFollowingSprite
	dba UNOWN_CFollowingSprite
	dba UNOWN_DFollowingSprite
	dba UNOWN_EFollowingSprite
	dba UNOWN_FFollowingSprite
	dba UNOWN_GFollowingSprite
	dba UNOWN_HFollowingSprite
	dba UNOWN_IFollowingSprite
	dba UNOWN_JFollowingSprite
	dba UNOWN_KFollowingSprite
	dba UNOWN_LFollowingSprite
	dba UNOWN_MFollowingSprite
	dba UNOWN_NFollowingSprite
	dba UNOWN_OFollowingSprite
	dba UNOWN_PFollowingSprite
	dba UNOWN_QFollowingSprite
	dba UNOWN_RFollowingSprite
	dba UNOWN_SFollowingSprite
	dba UNOWN_TFollowingSprite
	dba UNOWN_UFollowingSprite
	dba UNOWN_VFollowingSprite
	dba UNOWN_WFollowingSprite
	dba UNOWN_XFollowingSprite
	dba UNOWN_YFollowingSprite
	dba UNOWN_ZFollowingSprite
